server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adhd_helper?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

mybatis:
  configuration:
    map-underscore-to-camel-case: true
